## Numpy

(numeric python)

numpy.org

Czesc projektu scipy - scientific python

Udostępnia:
* klasy reprezentujące wektor i macierze (w tym specjalne wektory "atomowe" - elementy tego samego typu)
* przeróżne f-cje operujace na powyższych

Dodatkowe pakiety, ktore omowimy pozniej: scipy, matplotlib

Wykorzystuje (u)znane biblioteki: BLAS, LAPACK

pandas (ramki danych) tez bazuje na numpy

User Guide (do poczytanie): docs.scipy.org/doc/numpy/reference

In [1]:
!!aplay /home/samba/potockan/python/test.wav

["Playing WAVE '/home/samba/potockan/python/test.wav' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono"]

In [8]:
import numpy as np
# ndarray = n-dimensional array - homogeneusly typed
# x = np.array([...iterowalny obiekt...])

x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [9]:
x.ndim # liczba wymiarow

1

In [10]:
len(x) # liczba wszystkich elementow

3

In [11]:
x.dtype.name

'int64'

In [14]:
x.shape # liczba kolumn i wierszy

(3,)

In [15]:
x = x.astype(float)
x

array([ 1.,  2.,  3.])

In [17]:
x.dtype.name

'float64'

In [19]:
x.tolist()

[1.0, 2.0, 3.0]

In [20]:
np.array([1,2,3], dtype=float)

array([ 1.,  2.,  3.])

### Wazna f-cje

In [22]:
np.linspace(0,1,5) #seq z R seq(0,1,length.out=5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [24]:
np.arange(0, 10) #0:9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 10, 2.0) # seq(0,1,by=2)

array([ 0.,  2.,  4.,  6.,  8.])

In [28]:
np.__version__

'1.9.2'

In [30]:
A = np.array([
        [1,2,3],
        [4,5,6]], dtype=float)
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [32]:
A.shape

(2, 3)

In [33]:
A.ndim

2

In [35]:
A.shape = (2,3)
A

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [36]:
A.size

6

In [38]:
np.zeros(3) # rep(0,3)

array([ 0.,  0.,  0.])

In [39]:
np.zeros((3,2)) # macierz 3x2

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [40]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [41]:
np.empty((3,2)) #dowolne elementy

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [43]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [44]:
# operacje - element po elemencie
x

array([ 1.,  2.,  3.])

In [45]:
y = np.array([-1, 2, 4])

In [46]:
x + y

array([ 0.,  4.,  7.])

In [47]:
y = np.array([-1, 2, 4, 3, 2, 6])

In [48]:
x + y # brak reguly zawijania!

ValueError: operands could not be broadcast together with shapes (3,) (6,) 

In [49]:
x * 2

array([ 2.,  4.,  6.])

In [51]:
A * A # nie jest mnozenie macierzy, tylko element po elemencie

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [52]:
np.transpose(A)

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [54]:
np.dot(A, np.transpose(A)) # mnozenie macierzy

array([[ 14.,  32.],
       [ 32.,  77.]])

In [55]:
x *= -1
x

array([-1., -2., -3.])

In [64]:
# rep(5, 3)
a = np.array([5])
print(np.tile(a, 5))
# rep(c(1,2), 3)
a = np.array([1,2])
print(np.tile(a, 3))
# rep(c(1,2), each = 3)
print(np.repeat(a, [3, 3], axis=0))
print(np.repeat(a, [3, 2], axis=0))

[5 5 5 5 5]
[1 2 1 2 1 2]
[1 1 1 2 2 2]
[1 1 1 2 2]


In [63]:
#automatyczna promocja typow:
np.array([True, False]) * np.array([5,6])

array([5, 0])

In [66]:
# przeglad f-cji zwektoryzowanych (i metod)
# ufunc == f-cje "uniwersalne"
np.sin(np.linspace(0, 2*np.pi, 10))

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

In [67]:
# exp, sqrt, abs, ceil, floor, round, trunc, sign itd.

In [68]:
z = np.linspace(0, 2*np.pi, 10)
np.sin(z)

array([  0.00000000e+00,   6.42787610e-01,   9.84807753e-01,
         8.66025404e-01,   3.42020143e-01,  -3.42020143e-01,
        -8.66025404e-01,  -9.84807753e-01,  -6.42787610e-01,
        -2.44929360e-16])

In [69]:
z.round(3) #mozna np.f-cja(z) lub z.metoda(), bo duzo jest duplikatow

array([ 0.   ,  0.698,  1.396,  2.094,  2.793,  3.491,  4.189,  4.887,
        5.585,  6.283])

Czy lepiej np.funkcja czy tez obiekt.metoda?

* obiekt.metoda jest preferowane (może być szybciej, bo jest dopasowane do typu danych) 
* obiekt.metoda często modyfikuje obiekt w miejscu, a f-cja tworzy kopię
* z reguly robią to samo - ale mogą mieć różne zestawy argumentów

In [71]:
x = np.array([1,6,4,2,4,5])
np.sort(x)

array([1, 2, 4, 4, 5, 6])

In [72]:
x

array([1, 6, 4, 2, 4, 5])

In [73]:
x.sort()
x

array([1, 2, 4, 4, 5, 6])

In [74]:
# przekazywanie argumentow przez referencje
# glebokie kopiowanie np.: x.copy()
# ale nie (chyba): x[:] - robi plytka kopie

In [77]:
y = A[:] # nie jest to gleboka kopia

In [78]:
y

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [79]:
y[1,1] = 7

In [80]:
A

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  6.]])

In [81]:
print(id(A))
print(id(y)) #adres inny, ale obiekt ten sam

140626260447360
140626260059680


In [84]:
# f-cje agregujace:
# prod, sum, mean, cumprod, cumsum, diff
# argmax, argmin
# partition, searchsorted, argpartition?
x

array([1, 2, 4, 4, 5, 6])

In [92]:
np.select([x >= 5, x < 3], [1, 2], 3) # wybiera odpowiednie elementy

array([2, 2, 3, 3, 1, 1])

In [88]:
np.select([x>3], [-1], 3) #ifelse z R

array([ 3,  3, -1, -1, -1, -1])

In [93]:
import math
math.sin(3.14)

0.0015926529164868282

In [94]:
math.sin(np.array([3.14, 0])) # nie dziala na arrayach!

TypeError: only length-1 arrays can be converted to Python scalars

In [95]:
f_zwekt = np.vectorize(math.sin) #wektoryzuje f-cje
f_zwekt(np.array([3.14, 0]))

array([ 0.00159265,  0.        ])

## Indeksowanie i "slicing"

In [96]:
x = np.array([1,2,3,4,5])
x[0]

1

In [97]:
x[len(x)-1]

5

In [98]:
x[0:3]

array([1, 2, 3])

In [99]:
x[::2]

array([1, 3, 5])

In [100]:
x[[1,2,0,0,1]] #indeksowanie lista

array([2, 3, 1, 1, 2])

In [101]:
x[[-1, -2]] # ostatni, przedostatni

array([5, 4])

In [102]:
wektor_logiczny = x > 3
x[wektor_logiczny]

array([4, 5])

In [103]:
x = # 10 wartosci z N(0,1)
-1 < x < 1

SyntaxError: invalid syntax (<ipython-input-103-d26dd218d317>, line 1)

In [106]:
x = np.random.normal(0, 1, 10)
x

array([-1.56558556, -0.46247265, -1.00648947, -3.19542654, -0.07100518,
       -0.9145593 , -1.68313949, -0.20693179,  0.22891935, -1.19787074])

In [112]:
wektor_logiczny = (x > -1) * (x < 1) #(x > -1) & (x < 1)
x[wektor_logiczny]

array([-0.46247265, -0.07100518, -0.9145593 , -0.20693179,  0.22891935])

In [113]:
x[:,np.newaxis]

array([[-1.56558556],
       [-0.46247265],
       [-1.00648947],
       [-3.19542654],
       [-0.07100518],
       [-0.9145593 ],
       [-1.68313949],
       [-0.20693179],
       [ 0.22891935],
       [-1.19787074]])

In [183]:
# stworzyc wektor (1,2,3,4,5, 7,  0, 0.1, 0.2, ..., 1)
x = np.concatenate((
    np.append(np.linspace(1,5,5), 7), 
    np.linspace(0.1, 1, 10)))
x = np.concatenate((
    np.arange(1,5),
    np.array([7]),
    np.linspace(0.1, 1, 10)))
x = np.hstack((np.arange(0,5), 7, np.linspace(0,1,11)))
x = np.r_[0:5, 7, 0:1:11j] # j - na ile dzielisz, bez j - co ile chcesz
x

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  7. ,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [167]:
x[np.r_[1,3:5]]

array([ 0.9,  0.3,  0. ])

In [168]:
from numpy import r_ as c
c[0:3, 4]

array([0, 1, 2, 4])

In [153]:
# wybrac co drugi element z x
x[::2]

array([ 1. ,  3. ,  5. ,  0.1,  0.3,  0.5,  0.7,  0.9])

In [169]:
# zmienic znak na przeciwny co drugiego elementu
x[::2] *= (-1)
x

array([-7. ,  0.9, -0.4,  0.3, -0. ,  0.5, -3. ,  0.2, -0.6,  2. , -1. ,
        0.1, -1. ,  0.7, -4. ,  0. , -0.8])

In [166]:
# wyznaczyc losowa permutacje x
np.random.shuffle(x)
x

array([ 7. ,  0.9,  0.4,  0.3,  0. ,  0.5,  3. ,  0.2,  0.6,  2. ,  1. ,
        0.1,  1. ,  0.7,  4. ,  0. ,  0.8])

In [172]:
# dodac na koniec nowy element do x (losowy)
np.append(x, np.random.random(1)) #zwraca nowy

array([-7.        ,  0.9       , -0.4       ,  0.3       , -0.        ,
        0.5       , -3.        ,  0.2       , -0.6       ,  2.        ,
       -1.        ,  0.1       , -1.        ,  0.7       , -4.        ,
        0.        , -0.8       ,  0.69088416])

In [174]:
# na ktorych indeksach sa w x wartosci > 0
np.where(x > 0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [184]:
# wyznaczyc permutacje sortujaca
x.argsort()

array([ 0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,  1, 16,  2,  3,  4,  5])

In [185]:
x[x.argsort()]

array([ 0. ,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,
        1. ,  1. ,  2. ,  3. ,  4. ,  7. ])

In [178]:
A

array([[ 1.,  2.,  3.],
       [ 4.,  7.,  6.]])

In [179]:
np.where(A > 3)

(array([1, 1, 1]), array([0, 1, 2]))

In [180]:
A > 3

array([[False, False, False],
       [ True,  True,  True]], dtype=bool)

In [190]:
# posortuj x malejaco
x.sort()
x[::-1]

array([ 7. ,  4. ,  3. ,  2. ,  1. ,  1. ,  0.9,  0.8,  0.7,  0.6,  0.5,
        0.4,  0.3,  0.2,  0.1,  0. ,  0. ])

In [ ]:
# czy x jest posortowany?
# http://stackoverflow.com/questions/3755136/pythonic-way-to-check-if-a-list-is-sorted-or-not

In [191]:
# odwrocic kolejnosc elementow w x
x[::-1]

array([ 7. ,  4. ,  3. ,  2. ,  1. ,  1. ,  0.9,  0.8,  0.7,  0.6,  0.5,
        0.4,  0.3,  0.2,  0.1,  0. ,  0. ])

In [194]:
np.random.seed(123)
A = np.array(np.round(np.random.random(9), 2)).reshape(3,3)
A

array([[ 0.7 ,  0.29,  0.23],
       [ 0.55,  0.72,  0.42],
       [ 0.98,  0.68,  0.48]])

In [195]:
A[2,1]

0.68000000000000005

In [196]:
A[:,1]

array([ 0.29,  0.72,  0.68])

In [197]:
A[-1, :]

array([ 0.98,  0.68,  0.48])

In [198]:
A[np.ix_([1,2], [0,1])]

array([[ 0.55,  0.72],
       [ 0.98,  0.68]])

In [199]:
A.ravel() # unlist

array([ 0.7 ,  0.29,  0.23,  0.55,  0.72,  0.42,  0.98,  0.68,  0.48])

In [200]:
A.flat # iterator po ravel

In [201]:
A.T

array([[ 0.7 ,  0.55,  0.98],
       [ 0.29,  0.72,  0.68],
       [ 0.23,  0.42,  0.48]])

In [202]:
np.vstack((A, A)) # bind_row

array([[ 0.7 ,  0.29,  0.23],
       [ 0.55,  0.72,  0.42],
       [ 0.98,  0.68,  0.48],
       [ 0.7 ,  0.29,  0.23],
       [ 0.55,  0.72,  0.42],
       [ 0.98,  0.68,  0.48]])

In [203]:
np.hstack((A, A))

array([[ 0.7 ,  0.29,  0.23,  0.7 ,  0.29,  0.23],
       [ 0.55,  0.72,  0.42,  0.55,  0.72,  0.42],
       [ 0.98,  0.68,  0.48,  0.98,  0.68,  0.48]])

In [204]:
np.column_stack((A, np.array([1,2,3]))) # dokleja kolumne

array([[ 0.7 ,  0.29,  0.23,  1.  ],
       [ 0.55,  0.72,  0.42,  2.  ],
       [ 0.98,  0.68,  0.48,  3.  ]])

In [205]:
# nie ma brakow danych!
# poor man's missing values
x = np.array([1,2,3, np.NaN, 5])
x

array([  1.,   2.,   3.,  nan,   5.])

In [206]:
x.sum()

nan

In [207]:
np.nansum(x) #ignoruje NaNy

11.0