**Zadanie 1.** Przy uzyciu petli napisz funkcję movingavg(), która dla wektora x o $n$ elementach oraz nieparzystej liczby naturalnej $k$ wyznaczy $k$-średnią ruchomą, $k < n$, tj. ciag $(w_1,\dots,w_{n-k+1})$, dla którego $w_i=\sum_{j=1}^k x_{i+j-1}/k$.

In [19]:
import numpy as np

def movingavg(x, k):
    '''
    Funkcja liczy srednia ruchoma
    '''
    assert(len(x) > k)
    rozn = len(x) - k
    w = np.zeros(rozn)
    for i in range(rozn):
        w[i] = np.sum(x[i:(i+k)]) / k
    return w

In [20]:
print(movingavg(np.array(range(5)), 2))
print(movingavg(np.array(range(10)), 5))
print(movingavg(np.array(range(5)), 5))

[ 0.5  1.5  2.5]
[ 2.  3.  4.  5.  6.]


AssertionError: 

**Zadanie 2.** Napisz funkcje logiderle(), która jako argumenty przyjmuje równoliczne wektory całkowitoliczbowe i, j oraz wartość całkowitą $n$. Jeśli dla każdego możliwego $l$ nie zachodzi $1 \le i_l \le j_l \le n$ oraz $i_l > j_{l-1}$, natychmiast zakończ działanie błędem (raise Exception("komunikat")). Funkcja ma generować $n$-elementowy wektor logiczny w taki, że $w_l == \mathtt{True}$ wtw $(\exists p)$ $l\in[i_p; j_p]$. Dla przykładu, jeśli $n=7$, $\mathtt{i}=(1, 4)$, $\mathtt{j}=(1, 6)$, to w wyniku powinniśmy otrzymać łaskawie $(\mathtt{True},\mathtt{False},\mathtt{False}, \mathtt{True},\mathtt{True},\mathtt{True},\mathtt{False})$.

In [ ]:
import numpy as np

def logiderle(i, j, n):
    '''
    Generuje jakis dziwny wektor logiczny
    '''
    

In [25]:
i = np.array([1,4])
j = np.array([1,4])
n = 7
ni = len(i)
nj = len(j)
assert(ni == nj)
if !(all(i <= j)) or any(i < 1) or !(all(i[1:] > j[:-1])):
    raise Exception("Niespelnione warunki zadania!")
w = np.zeros(n)
# TO DO...
#for k in range(n):
    #w[i] = 

array([ True, False], dtype=bool)

array([4])