In [1]:
import scipy.io.wavfile
import os
import numpy as np
os.getcwd()

'/home/npotocka/mgr/Text-clustering-basing-on-string-metrics/Python/padpy/pd3'

In [13]:
fs1, y1 = scipy.io.wavfile.read("../Snare-Drum-2.wav")
fs2, y2 = scipy.io.wavfile.read("../Side-Stick-4.wav")
fs3, y3 = scipy.io.wavfile.read("../Deep-Kick.wav")
fs = fs1
y1 = np.tile(y1[:len(y1/2)], 2)
y2 = np.tile(y2[:len(y2/2)], 2)
y3 = np.tile(y3[:len(y3/2)], 2)
y = np.r_[y1, y2]
#y = np.repeat(y, 4, axis = 0)
y = np.tile(y, [4,4])
y = np.mean(y, axis=1)
y /= 32767


scipy.io.wavfile.write("../test8.wav", 
                       fs, 
                       np.int16(y/max(np.abs(y))*32767))
!!aplay ../test8.wav

/home/natalia/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


["Playing WAVE '../test8.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono"]

In [2]:
with open('utwor1/song.txt', 'r') as f:
    song = f.read()
song

'01\n01\n02\n01\n01\n02\n'

In [3]:
tracks = []
for i in song.splitlines():
    with open('utwor1/track' + i +'.txt', 'r') as f:
           tracks += (f.read().splitlines())
            
print(tracks)

['01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '-- -- -- --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '-- -- -- --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '-- -- -- --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '-- -- -- --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --']


In [4]:
sample = []
for i in set(tracks):
    sample += i.split()
sample = [i for i in list(set(sample)) if i != '--']
sample.sort()
print(sample)

['01', '02', '03', '04']


In [5]:
fs = []
y = []
for i, s in enumerate(sample):
    fs1, y1 = scipy.io.wavfile.read('./utwor1/sample' + s + '.wav')
    fs.append(fs1)
    y.append(y1)
    
for x in y:
    print(x.shape) 
    
s = min([x.shape[0] for x in y])
y = [x[:s] for x in y]
# y2 = np.zeros((1, 4))

# for x in y:
#     y2 = np.r_[y2 + np.tile(x, 2)]

(25448, 2)
(115535, 2)
(13038, 2)
(15313, 2)


/home/npotocka/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


In [12]:
y2 = np.zeros(1)
for a,i in enumerate(tracks):
    idx = {x for x in set(i.split()) if x != '--'}
    if idx:
        #idx
        kk = []
        for j in idx:
            kk.append(sample.index(j))
        y3 = np.zeros(1)
        for x in kk:
            y3 = np.r_[y3 + np.tile(y[x], 2)]
        if a == 0:
            y2 = y3.copy()
        y2 = np.r_[y2,y3]
    else:
        y2 = np.r_[y2,np.zeros((s, 4))]
    
print(y2.shape)

(847470, 4)


In [13]:
print(y2)
y2 = np.mean(y2, axis=1)
y2 /= 32767
print(y2.dtype)
print(type(np.int16(y2/max(np.abs(y2))*32767)))
print(y2)
print(np.int16(y2/max(np.abs(y2))*32767))
print(y2.shape)
#?scipy.io.wavfile.write

scipy.io.wavfile.write("pd_proba1.wav", 
                       fs[0], 
                       np.int16(y2/max(np.abs(y2))*32767))
!!aplay pd_proba1.wav
os.remove("pd_proba1.wav")

[[ -103.   -44.  -103.   -44.]
 [  -97.  -235.   -97.  -235.]
 [  994.   493.   994.   493.]
 ..., 
 [-1066. -2108. -1066. -2108.]
 [-1126. -1967. -1126. -1967.]
 [-1072. -1712. -1072. -1712.]]
float64
<class 'numpy.ndarray'>
[-0.00224311 -0.00506607  0.02269051 ..., -0.04843287 -0.04719687
 -0.04248177]
[  -48  -110   494 ..., -1055 -1028  -925]
(847470,)
