In [90]:
import scipy.io.wavfile
import os
import numpy as np
os.getcwd()

'/home/npotocka/mgr/Text-clustering-basing-on-string-metrics/Python/padpy/pd3'

In [13]:


fs1, y1 = scipy.io.wavfile.read("../Snare-Drum-2.wav")
fs2, y2 = scipy.io.wavfile.read("../Side-Stick-4.wav")
fs3, y3 = scipy.io.wavfile.read("../Deep-Kick.wav")
fs = fs1
y1 = np.tile(y1[:len(y1/2)], 2)
y2 = np.tile(y2[:len(y2/2)], 2)
y3 = np.tile(y3[:len(y3/2)], 2)
y = np.r_[y1, y2]
#y = np.repeat(y, 4, axis = 0)
y = np.tile(y, [4,4])
y = np.mean(y, axis=1)
y /= 32767


scipy.io.wavfile.write("../test8.wav", 
                       fs, 
                       np.int16(y/max(np.abs(y))*32767))
!!aplay ../test8.wav

/home/natalia/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


["Playing WAVE '../test8.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono"]

In [91]:
with open('utwor1/song.txt', 'r') as f:
    song = f.read()
song

'01\n01\n02\n01\n01\n02\n'

In [92]:
tracks = []
for i in song.splitlines():
    with open('utwor1/track' + i +'.txt', 'r') as f:
           tracks += (f.read().splitlines())
            
print(tracks)

['01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '-- -- 03 --', '-- 02 03 --', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- -- 03 --', '-- 02 03 --', '01 02 03 04', '01 -- 03 04', '01 -- 03 --', '-- 02 03 --']


In [93]:
sample = []
for i in set(tracks):
    sample += i.split()
sample = [i for i in list(set(sample)) if i != '--']
print(sample)

['04', '03', '01', '02']


In [94]:
fs = []
y = []
for i, s in enumerate(sample):
    fs1, y1 = scipy.io.wavfile.read('./utwor1/sample' + s + '.wav')
    fs.append(fs1)
    y.append(y1)
    
for x in y:
    print(x.shape) #### TO DO HERE
    
s = min([x.shape[0] for x in y])
y = [x[:s] for x in y]
y2 = np.zeros(1)
for x in y:
    y2 = np.r_[y2 + np.tile(x, 2)]

(15313, 2)
(13038, 2)
(25448, 2)
(115535, 2)


/home/npotocka/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


In [95]:
# y2 = np.r_[np.tile(y[0][:s], 2) +
#            np.tile(y[1][:s], 2) + 
#            np.tile(y[2][:s], 2) + 
#            np.tile(y[3][:s], 2)]#np.tile(y1[:len(y1/2)], 2)
print(y2)
y2 = np.mean(y2, axis=1)
y2 /= 32767
print(y2.dtype)
print(type(np.int16(y2/max(np.abs(y2))*32767)))
print(y2)
print(np.int16(y2/max(np.abs(y2))*32767))
print(y2.shape)
#?scipy.io.wavfile.write

scipy.io.wavfile.write("pd_proba1.wav", 
                       fs[0], 
                       np.int16(y2/max(np.abs(y2))*32767))
!!aplay pd_proba1.wav

[[ -103.   -44.  -103.   -44.]
 [  -97.  -235.   -97.  -235.]
 [  994.   493.   994.   493.]
 ..., 
 [ -748. -2151.  -748. -2151.]
 [ -767. -1982.  -767. -1982.]
 [ -678. -1707.  -678. -1707.]]
float64
<class 'numpy.ndarray'>
[-0.00224311 -0.00506607  0.02269051 ..., -0.04423658 -0.04194769
 -0.03639332]
[ -48 -110  494 ..., -963 -913 -792]
(13038,)


["Playing WAVE 'pd_proba1.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono"]

In [16]:
### SMIECI PONIZEJ


fs1, y1 = scipy.io.wavfile.read("../Snare-Drum-2.wav")
fs2, y2 = scipy.io.wavfile.read("../Side-Stick-4.wav")
fs3, y3 = scipy.io.wavfile.read("../Deep-Kick.wav")
print(y2)

[[ -2  -2]
 [ -2   0]
 [ -4  -2]
 ..., 
 [-16 -25]
 [  0  -4]
 [  9   2]]


/home/npotocka/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


In [39]:
f = 

y = np.r_[np.sin(2*np.pi*f*t) +
          np.sin(2*np.pi*f*(const**3)*t) +
          np.sin(2*np.pi*f*(const**7)*t) ]

scipy.io.wavfile.write("test4.wav", 
                       fs, 
                       np.int16(y/max(np.abs(y))*32767))
!!aplay /home/samba/potockan/python/test4.wav

TypeError: unsupported operand type(s) for *: 'float' and '_io.TextIOWrapper'

In [49]:
tracks[1].split(' ')

['--', '--', '03', '--']

In [71]:
fs1, y1 = scipy.io.wavfile.read("../Snare-Drum-2.wav")
fs2, y2 = scipy.io.wavfile.read("../Side-Stick-4.wav")
fs3, y3 = scipy.io.wavfile.read("../Deep-Kick.wav")
fs = fs1
y1 = np.tile(y1[:len(y1/2)], 2)
y2 = np.tile(y2[:len(y2/2)], 2)
y3 = np.tile(y3[:len(y3/2)], 2)
y = np.r_[y1, y2]
print(y)
#y = np.repeat(y, 4, axis = 0)
y = np.tile(y, [4,4])
y = np.mean(y, axis=1)
print(y)
y /= 32767
print(y.shape)

scipy.io.wavfile.write("test8.wav", 
                       fs, 
                       np.int16(y/max(np.abs(y))*32767))
!!aplay test8.wav

[[ 30  38  30  38]
 [-37 -44 -37 -44]
 [ 46  54  46  54]
 ..., 
 [-16 -25 -16 -25]
 [  0  -4   0  -4]
 [  9   2   9   2]]
[ 34.  -40.5  50.  ..., -20.5  -2.    5.5]
(113404,)


/home/npotocka/anaconda3/lib/python3.4/site-packages/scipy/io/wavfile.py:172: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


["Playing WAVE 'test8.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono"]